spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${PROD_SQL_DATABASE_URL}
    username: ${PROD_SQL_DATABASE_USERNAME}
    password: ${PROD_SQL_DATABASE_PASSWORD}

    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      maximum-pool-size: 10
      #      minimum-idle: 10
      connection-timeout: 5000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: hikari_pool

server:
  port: 80
  servlet:
    session:
      timeout: 5000

management:
  endpoint:
    logfile:
      external-file: ~/logback.log
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,mappings,threaddump,conditions,info,heapdump
      base-path: /api/actuator
      path-mapping:
        loggers: logs
        httptrace: trace

discord:
  bot:
    secretToken: ${PROD_DISCORD_BOT_SECRET_TOKEN}