name: Deploy-prod-server
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths:
      - "application/**"
      - "domain/**"
      - "infrastructure/**"
      - "*.gradle.kts"

permissions:
  contents: read

env:
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            application:
              - 'application/**'
            domain:
              - 'domain/**'
            infrastructure:
              - 'infrastructure/**'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test all
        run: ./gradlew clean :application:test domain:test infrastructure:test

      - name: Compile
        run: ./gradlew clean :application:build -x test

      - name: Emulator install
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx for Arm64
        uses: docker/setup-buildx-action@v3

      - name: Harbor registry login
        uses: docker/login-action@v3
        with:
          registry: harbor.registry.notypie.dev
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push build image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: ./application
          push: true
          tags: |
            harbor.registry.notypie.dev/bot/discord-study-manager:${{ env.DOCKER_TAG }}
  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH access and Execute deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLUSTER_DEPLOY_HOST }}
          username: ${{ secrets.CLUSTER_DEPLOY_USER }}
          key: ${{ secrets.CLUSTER_PRIV_KEY }}
          port: 22
          script: |
            cd actions
            ./deploy.sh studymanager ${{ env.DOCKER_TAG }} ${{ secrets.AUTHORIZE_KEY }}