#name: Deploy-dev-server
#on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - "develop"
#    paths:
#      - "application/**"
#      - "domain/**"
#      - "infrastructure/**"
#      - "*.gradle.kts"
#
#permissions:
#  contents: read
#
#env:
#  DOCKER_TAG: ${{ github.sha }}
#
#jobs:
#  build:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dorny/paths-filter@v3
#        id: changes
#        with:
#          filters: |
#            application:
#              - 'application/**'
#            domain:
#              - 'domain/**'
#            infrastructure:
#              - 'infrastructure/**'
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Test all
#        run: ./gradlew clean :application:test domain:test infrastructure:test
#
#      - name: Compile
#        run: ./gradlew clean :application:build -x test
#
#
#      - name: Harbor registry login
#        uses: docker/login-action@v3
#        with:
#          registry: harbor.registry.notypie.dev
#          username: ${{ secrets.REGISTRY_USER }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}
#
#      - name: Push build image
#        uses: docker/build-push-action@v5
#        with:
#          platforms: linux/amd64
#          context: ./application
#          push: true
#          tags: |
#            harbor.registry.notypie.dev/bot/discord-study-manager:${{ env.DOCKER_TAG }}
#
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
